### PR TITLE
Add tests of kmath-memory and make all the memory operations on all the platforms use little-endian byte order

### PR DESCRIPTION
**Pull request by CommanderTvis**

### CODE REVIEW

**Review by altavir — CHANGES_REQUESTED** [review]
Keeping endians across platform does not make any sense. It is possible to define additional memory, that is shareable between platforms, but I do not want to guarantee that for the default memory.

**Comment by CommanderTvis** [comment]
> Keeping endians across platform does not make any sense. It is possible to define additional memory, that is shareable between platforms, but I do not want to guarantee that for the default memory.

It does. We provide ways to wrap existing object as memory (Memory.wrap), and it has to work equally on all the supported platforms.

**Comment by CommanderTvis** [comment]
e.g., `Memory.wrap(byteArrayOf(0,0,0,1)).read { readInt(0) }` must be persistent

**Comment by altavir** [comment]
I can't see, why it should. We do not allow to access the inner layout of memory, only the offset.

**Comment by CommanderTvis** [comment]
> I can't see, why it should. We do not allow to access the inner layout of memory, only the offset.

Because it's almost useless it is does not because each platform must receive separate byte arrays.

**Comment by CommanderTvis** [comment]
Why do we need wrapping of array if it works in absolutely different way on each platform

**Comment by altavir** [comment]
Currently, Memory is the inner implementation detail. Do we even need wrapping of arrays?

**Comment by CommanderTvis** [comment]
We may drop it as well as file reading in JVM

**Comment by altavir** [comment]
File reading does not break any rules, but I agree it is useless right now, so it could be commented out.

**Comment by CommanderTvis** [comment]
Stale PR, the problem itself has to be discussed

**Pull request closed without merging**
