### PR TITLE
Jacobi eigenvalue algorithm

### PR DESCRIPTION
**Pull request by ivandev0**
Instead of using the SVD to compute the eigendecomposition of a real symmetric matrix, I implemented the Jacobi's method.

Tested correctness of algorithm with `space.kscience.kmath.tensors.core.TestDoubleLinearOpsTensorAlgebra` test. Not sure about performance, it require further investigation. Maybe it is worth to implement cyclic Jacobi algorithm.

### CODE REVIEW

**Comment by grinisrit** [comment]
@ivandev0 you might have a look at this implementation: https://github.com/mipt-npm-study/numerics-2021/blob/master/jacobi.cc

**Comment by CommanderTvis** [comment]
Changed the base to not affect `master` again.

**Comment by ivandev0** [comment]
So, I fixed it. In my opinion It is harder to read current code, but it is 10x faster than SVD :)
```
Benchmark                                   Mode  Cnt    Score    Error  Units
TensorAlgebraBenchmark.tensorSymEigJacobi  thrpt    5  567.582 ± 37.343  ops/s
TensorAlgebraBenchmark.tensorSymEigSvd     thrpt    5   47.725 ±  3.372  ops/s
```

**Comment by ivandev0** [comment]
This last commit is not about Jacobi algorithm but mostly an addition to my previous PR. I figured out that `tensor` and `matrix` are kind of the same type and dispatch to real `dot` depends on used algebra (please fix me if I am wrong). So I dropped duplicate test that I added.

**Review by grinisrit — APPROVED** [review]

**Review by altavir — APPROVED** [review]

**Pull request merged**
